<form action="registration" method="post">
    <label for="name">Imię: </label>
    <input type="text" name="name" value="<?=$registration['name']?>" required><br/>
    <label for="mail">E-mail: </label>
    <input type="email" name="mail" value="<?=$registration['mail']?>" required><br/>
    <label for="login">Login: </label>
    <input type="text" name="login" value="<?=$registration['login']?>" required><br/>
    <label for="password">Hasło: </label>
    <input type="password" name="password" required><br/>
    <label for="password">Powtórz hasło: </label>
    <input type="password" name="reppassword" required><br/>
    <input class="navButton" type="submit" value="Zarejestruj"/>
</form>
